
/**
 * Author:  Admin
 * Created: 22 mai 2019
 */

CREATE TABLE Ecole(Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, Nom varchar(50) NOT NULL);
CREATE TABLE Niveau(Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, Nom varchar(50) NOT NULL);
CREATE TABLE Discipline(Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, Nom varchar(50) NOT NULL);

CREATE TABLE AnneeScolaire(Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, annee int NOT NULL);
CREATE TABLE Trimestre(Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, Numero int NOT NULL, Debut DATE NOT NULL, Fin DATE NOT NULL,annee int NOT NULL, FOREIGN KEY(annee) REFERENCES annee(Id));
CREATE TABLE Classe(Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, Nom varchar(50) NOT NULL, ecole int NOT NULL, FOREIGN KEY(ecole) REFERENCES ecole(Id), niveau int NOT NULL, FOREIGN KEY(niveau) REFERENCES niveau(Id),annee int NOT NULL, FOREIGN KEY(annee) REFERENCES annee(Id));
CREATE TABLE Enseignement(Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT);

CREATE TABLE Personne(Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, Nom varchar(50) NOT NULL,Prenom varchar(50) NOT NULL);
CREATE TABLE Enseignant(Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT);
CREATE TABLE Eleve(personne int NOT NULL, FOREIGN KEY(personne) REFERENCES personne(Id)));


CREATE TABLE Inscription(Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT);
CREATE TABLE Bulletin(Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT);

CREATE TABLE Evaluation(Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT);
CREATE TABLE Discipline(Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT);
CREATE TABLE DetailBulletin(Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT);













